name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Debug show run context and workspace
        shell: bash
        run: |
          echo "GITHUB_RUN_ID=${{ github.run_id }}"
          echo "GITHUB_RUN_NUMBER=${{ github.run_number }}"
          echo "GITHUB_WORKFLOW=${{ github.workflow }}"
          echo "Workspace: $GITHUB_WORKSPACE"
          pwd
          ls -la
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build & Deploy
        uses: actions/upload-pages-artifact@v4
        with:
          path: .
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
